// Questões inéditas no estilo Cesgranrio, geradas pela rotina diária "Simulados Transpetro".
// Mantido automaticamente pela rotina: não editar à mão. Ids a partir de 10001.
// Cada item segue o formato de data.js + "origem": "ia", "rodada" e "dataCriacao".
const QUESTOES_IA = [
  {
    "id": 10001,
    "materia": "Português",
    "assunto": "Interpretação de texto",
    "enunciado": "1. De acordo com o texto, o controle de qualidade em processos administrativos:",
    "alternativas": [
      "deve se concentrar exclusivamente na verificação dos resultados finais de cada processo.",
      "é dispensável em organizações públicas que já possuem órgãos de controle externo.",
      "deve estar presente em todas as etapas da rotina de trabalho, e não apenas no resultado final.",
      "é incompatível com a padronização de rotinas administrativas.",
      "aplica-se apenas a contratos de grande vulto, dispensando documentos rotineiros como ofícios."
    ],
    "corretaIndex": 2,
    "regra": "O texto abre negando exatamente a alternativa (A): \"não se resume à verificação de resultados finais; ele deve permear cada etapa da rotina de trabalho, da elaboração de um simples ofício à assinatura de um contrato de grande vulto\". Isso confirma a alternativa (C) e descarta (A) e (E), que restringem o controle a apenas uma parte do processo. As alternativas (B) e (D) invertem relações apresentadas no texto: o controle externo pressupõe controle interno bem feito, e a padronização é chamada de \"aliada da eficiência\", não de algo incompatível com ela.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q1"
  },
  {
    "id": 10002,
    "materia": "Português",
    "assunto": "Interpretação de texto",
    "enunciado": "2. O conectivo \"Ainda que\", no trecho \"Ainda que a burocracia seja frequentemente associada a lentidão e a excesso de formalismo, quando bem estruturada, ela cumpre a função de reduzir riscos [...]\", estabelece entre as orações uma relação de:",
    "alternativas": [
      "causa",
      "concessão",
      "conformidade",
      "finalidade",
      "proporcionalidade"
    ],
    "corretaIndex": 1,
    "regra": "\"Ainda que\" é conjunção subordinativa concessiva (equivalente a \"embora\", \"conquanto\", \"mesmo que\"): introduz uma ideia que poderia contrariar a oração principal, mas não a impede de se realizar — aqui, a má fama da burocracia não impede que ela, bem estruturada, reduza riscos. Não é causa, finalidade, conformidade nem proporcionalidade.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q2"
  },
  {
    "id": 10003,
    "materia": "Português",
    "assunto": "Interpretação de texto",
    "enunciado": "3. No trecho \"Tal rastreabilidade, aliás, revela-se indispensável [...]\", o termo destacado retoma, no texto, a ideia de:",
    "alternativas": [
      "a lentidão associada à burocracia.",
      "a capacidade de reduzir riscos e evitar retrabalho.",
      "a possibilidade de reconstituir o histórico e a origem de decisões administrativas.",
      "a substituição da governança corporativa pelo controle externo.",
      "a eliminação total da formalidade nos processos públicos."
    ],
    "corretaIndex": 2,
    "regra": "\"Rastreabilidade\" é a capacidade de rastrear — reconstituir o histórico, a origem e o percurso — de um processo ou decisão; o pronome demonstrativo \"Tal\" retoma anaforicamente o termo \"rastreabilidade às decisões administrativas\", citado na frase anterior.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q3"
  },
  {
    "id": 10004,
    "materia": "Português",
    "assunto": "Concordância verbal",
    "enunciado": "4. Assinale a alternativa em que a concordância verbal está de acordo com a norma-padrão da língua portuguesa:",
    "alternativas": [
      "Mais de um setor apresentaram falhas na conformidade documental.",
      "Fazem dois anos que o novo sistema de controle interno foi implementado.",
      "Deve haver mais controles internos nesse processo.",
      "Haviam muitos documentos pendentes de análise.",
      "Existe, no órgão, diversas normas de controle interno desatualizadas."
    ],
    "corretaIndex": 2,
    "regra": "O verbo \"haver\" no sentido de existir é impessoal e fica sempre na 3ª pessoa do singular, mesmo com auxiliar (\"deve haver\"). \"Fazer\" indicando tempo decorrido também é impessoal: o certo em (B) seria \"Faz dois anos\". \"Mais de um\" + singular exige verbo singular: certo em (A) seria \"apresentou\". \"Existir\" é pessoal: certo em (E) seria \"Existem\".",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q4"
  },
  {
    "id": 10005,
    "materia": "Português",
    "assunto": "Concordância nominal",
    "enunciado": "5. Assinale a alternativa em que a concordância nominal está de acordo com a norma-padrão da língua portuguesa:",
    "alternativas": [
      "Seguem anexas ao processo as cópias dos contratos solicitados.",
      "As certidões necessárias estão anexo ao ofício.",
      "Ela mesmo revisou todos os documentos antes de protocolar o processo.",
      "Os servidores ficaram meia surpresos com o resultado da auditoria.",
      "Muito obrigada, disse o servidor ao concluir a entrega dos documentos."
    ],
    "corretaIndex": 0,
    "regra": "\"Anexo\", \"mesmo\" e \"obrigado\" concordam em gênero/número com o substantivo. Em (A), \"anexas\" concorda com \"as cópias\". Em (B) o certo seria \"anexas\"; em (C), \"ela mesma\"; em (E), \"muito obrigado\". \"Meio\" advérbio é invariável — certo em (D) seria \"meio surpresos\".",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q5"
  },
  {
    "id": 10006,
    "materia": "Português",
    "assunto": "Regência verbal",
    "enunciado": "6. Assinale a alternativa em que a regência verbal está de acordo com a norma-padrão da língua portuguesa:",
    "alternativas": [
      "O atraso na entrega dos documentos implicou em advertência ao responsável pelo setor.",
      "Os servidores assistiram a palestra sobre compliance na sede da empresa.",
      "O novo gestor visava a modernização dos processos internos.",
      "O atraso na entrega dos documentos implicou advertência ao responsável pelo setor.",
      "O servidor aspira o cargo de coordenador de controle interno há dois anos."
    ],
    "corretaIndex": 3,
    "regra": "\"Implicar\" (acarretar) é transitivo direto: certo em (D). \"Assistir\" (ver) pede \"a\": certo em (B) seria \"assistiram à palestra\". \"Visar\" (ter como objetivo) pede \"a\": certo em (C) seria \"visava à modernização\". \"Aspirar\" (desejar) pede \"a\": certo em (E) seria \"aspira ao cargo\".",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q6"
  },
  {
    "id": 10007,
    "materia": "Português",
    "assunto": "Regência nominal",
    "enunciado": "7. Assinale a alternativa em que a regência nominal — a relação entre o nome e a preposição que ele exige — está de acordo com a norma-padrão:",
    "alternativas": [
      "O procedimento adotado é compatível às normas internas de controle.",
      "Os servidores mostraram-se obedientes com as novas diretrizes de compliance.",
      "A equipe está orgulhosa do resultado obtido na última auditoria.",
      "O novo procedimento é diferente ao adotado anteriormente pelo setor.",
      "A proposta é favorável para os interesses do órgão fiscalizador."
    ],
    "corretaIndex": 2,
    "regra": "\"Orgulhoso\" rege \"de\": certo em (C). \"Compatível\" rege \"com\": certo em (A) seria \"compatível com\". \"Obediente\" rege \"a\": certo em (B) seria \"obedientes às\". \"Diferente\" rege \"de\": certo em (D) seria \"diferente do\". \"Favorável\" rege \"a\": certo em (E) seria \"favorável aos\".",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q7"
  },
  {
    "id": 10008,
    "materia": "Português",
    "assunto": "Crase",
    "enunciado": "8. Assinale a alternativa em que o uso (ou a ausência) do acento indicativo de crase está de acordo com a norma-padrão:",
    "alternativas": [
      "O relatório foi encaminhado à Diretoria de Controle Interno.",
      "O servidor não compareceu à trabalho na data prevista.",
      "A auditoria será realizada à partir de segunda-feira.",
      "Esse procedimento é semelhante à aquele adotado no ano anterior.",
      "Cabe à cada servidor revisar seus próprios documentos."
    ],
    "corretaIndex": 0,
    "regra": "Há crase pela fusão da preposição \"a\" com o artigo \"a\": em (A), \"à Diretoria\" está correto. Não há crase antes de palavra masculina (B), na locução \"a partir de\" (C, sempre sem crase), antes de \"aquele\" masculino (D) nem antes de \"cada\" (E).",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q8"
  },
  {
    "id": 10009,
    "materia": "Português",
    "assunto": "Colocação pronominal",
    "enunciado": "9. Assinale a alternativa em que a colocação pronominal está de acordo com a norma-padrão da língua portuguesa:",
    "alternativas": [
      "Nunca se recusaram os pedidos de vista aos autos do processo.",
      "Recusaram-se nunca os pedidos de vista aos autos do processo.",
      "Todos aqueles que omitiram-se na prestação de contas serão notificados.",
      "Quando o processo concluir-se, o parecer final será encaminhado.",
      "Embora tenha-se esforçado bastante, o servidor não obteve o resultado esperado."
    ],
    "corretaIndex": 0,
    "regra": "Palavras atrativas (negação, pronome relativo, conjunção subordinativa) exigem próclise. Em (A), \"Nunca se recusaram\" está correto. As demais alternativas usam ênclise indevidamente após palavra atrativa.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q9"
  },
  {
    "id": 10010,
    "materia": "Português",
    "assunto": "Acentuação gráfica",
    "enunciado": "10. Assinale a alternativa em que todas as palavras seguem a mesma regra de acentuação gráfica:",
    "alternativas": [
      "português, também, ninguém",
      "razão, também, ninguém",
      "também, ninguém, armazém",
      "fácil, útil, também",
      "história, fácil, país"
    ],
    "corretaIndex": 2,
    "regra": "\"Também\", \"ninguém\" e \"armazém\" são oxítonas terminadas em \"EM\" tônico — mesma regra, por isso (C) está correta. As demais alternativas misturam regras de acentuação distintas.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 4 — 2026-09-17",
    "fonteUrl": "https://claude.ai/artifact/Mzn1sVNuT72HoetzSkc2MY",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-17",
    "idOrigem": "Língua Portuguesa|R4|Q10"
  },
  {
    "id": 10011,
    "materia": "Português",
    "assunto": "Interpretação de texto",
    "enunciado": "1. De acordo com o texto, a gestão de riscos operacionais:",
    "alternativas": [
      "deve atuar apenas após a ocorrência de incidentes, para mitigar danos já causados.",
      "pressupõe identificação antecipada de vulnerabilidades ao longo de toda a cadeia produtiva, não se limitando à reação a incidentes.",
      "é dispensável quando há programas de manutenção preditiva implementados.",
      "elimina por completo a possibilidade de eventos adversos, quando bem estruturada.",
      "restringe-se exclusivamente à etapa de extração, sem alcançar transporte, refino e distribuição."
    ],
    "corretaIndex": 1,
    "regra": "O texto nega exatamente a ideia de reação tardia: 'não se limita à reação diante de incidentes já ocorridos; ela pressupõe, antes de tudo, a identificação antecipada de vulnerabilidades ao longo de toda a cadeia produtiva'. Isso confirma (B) e descarta (A) e (E). A alternativa (C) inverte a relação e (D) contraria o texto, que afirma que os programas 'não eliminam por completo a possibilidade de eventos adversos'.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q1"
  },
  {
    "id": 10012,
    "materia": "Português",
    "assunto": "Interpretação de texto",
    "enunciado": "2. O conectivo 'embora', no trecho 'reduzem significativamente a probabilidade de falhas graves, embora não eliminem por completo a possibilidade de eventos adversos', estabelece entre as orações uma relação de:",
    "alternativas": [
      "causa",
      "concessão",
      "consequência",
      "condição",
      "finalidade"
    ],
    "corretaIndex": 1,
    "regra": "'Embora' é conjunção subordinativa concessiva (equivalente a 'ainda que', 'conquanto', 'mesmo que'): introduz ideia que poderia contrariar a oração principal, mas não a impede de se realizar.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q2"
  },
  {
    "id": 10013,
    "materia": "Português",
    "assunto": "Interpretação de texto",
    "enunciado": "3. No trecho 'Tal planejamento, contudo, exige revisão constante [...]', o termo destacado retoma, no texto, a ideia de:",
    "alternativas": [
      "a manutenção preditiva isoladamente.",
      "a auditoria periódica das equipes.",
      "o plano de continuidade de negócio mencionado no período anterior.",
      "a extração de petróleo.",
      "a probabilidade de falhas graves."
    ],
    "corretaIndex": 2,
    "regra": "O pronome demonstrativo 'Tal' retoma anaforicamente 'um plano de continuidade de negócio', citado na frase anterior.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q3"
  },
  {
    "id": 10014,
    "materia": "Português",
    "assunto": "Concordância verbal",
    "enunciado": "4. Assinale a alternativa em que a concordância verbal está de acordo com a norma-padrão da língua portuguesa:",
    "alternativas": [
      "Fazem cinco anos que o plano de continuidade foi revisado pela última vez.",
      "Existem, no plano, diversas medidas de mitigação ainda não implementadas.",
      "Deve haverem mais auditorias nesse setor.",
      "Alugam-se equipamentos de segurança para as equipes de campo, mas aluga-se poucos.",
      "Vão fazer dois meses desde a última auditoria externa."
    ],
    "corretaIndex": 1,
    "regra": "'Existir' é pessoal e concorda com o sujeito: 'Existem diversas medidas' está correto. 'Fazer' (tempo decorrido) e 'haver' (existir) são impessoais, sempre singular: (A) 'Faz cinco anos', (C) 'Deve haver', (E) 'Vai fazer dois meses'. Em (D), 'aluga-se poucos' deveria ser 'alugam-se poucos'.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q4"
  },
  {
    "id": 10015,
    "materia": "Português",
    "assunto": "Concordância nominal",
    "enunciado": "5. Assinale a alternativa em que a concordância nominal está de acordo com a norma-padrão da língua portuguesa:",
    "alternativas": [
      "As medidas de segurança seguem anexas ao relatório de auditoria.",
      "As não conformidades identificadas ficaram meias resolvidas até o prazo final.",
      "Os documentos originais e a ata estão anexo ao processo.",
      "Ela mesmo elaborou o plano de continuidade sem apoio da equipe.",
      "Bastante funcionários participaram do treinamento de segurança."
    ],
    "corretaIndex": 0,
    "regra": "'Anexo' concorda com o substantivo: 'anexas' concorda com 'as medidas'. Em (B) 'meio' advérbio é invariável ('meio resolvidas'); em (C) deveria ser 'anexos' (dois substantivos); em (D) 'ela mesma'; em (E) 'bastantes funcionários'.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q5"
  },
  {
    "id": 10016,
    "materia": "Português",
    "assunto": "Regência verbal",
    "enunciado": "6. Assinale a alternativa em que a regência verbal está de acordo com a norma-padrão da língua portuguesa:",
    "alternativas": [
      "O gestor visou à aprovação do novo plano de continuidade de negócio.",
      "A equipe assistiu a reunião de análise crítica de riscos na sede da empresa.",
      "O relatório de auditoria implica em advertência aos responsáveis pelo setor.",
      "Os técnicos preferem o treinamento presencial do que o virtual.",
      "Os servidores aspiram o cargo de coordenador de riscos operacionais."
    ],
    "corretaIndex": 0,
    "regra": "'Visar' (ter como objetivo) rege 'a': 'visou à aprovação' correto. (B) 'assistir' rege 'a' ('assistiu à reunião'); (C) 'implicar' é transitivo direto (sem 'em'); (D) 'preferir X a Y' (não 'do que'); (E) 'aspirar' rege 'a' ('aspiram ao cargo').",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q6"
  },
  {
    "id": 10017,
    "materia": "Português",
    "assunto": "Regência nominal",
    "enunciado": "7. Assinale a alternativa em que a regência nominal está de acordo com a norma-padrão da língua portuguesa:",
    "alternativas": [
      "O plano de continuidade é compatível com as diretrizes internacionais de gestão de riscos.",
      "A equipe de auditoria está atenta com os indícios de não conformidade.",
      "Essa solução é diferente à adotada no ano anterior.",
      "O gestor mostrou-se receoso com os resultados da auditoria externa.",
      "A proposta é favorável para os interesses da diretoria executiva."
    ],
    "corretaIndex": 0,
    "regra": "'Compatível' rege 'com': correto em (A). (B) 'atento' rege 'a'; (C) 'diferente' rege 'de'; (D) 'receoso' rege 'de'; (E) 'favorável' rege 'a'.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q7"
  },
  {
    "id": 10018,
    "materia": "Português",
    "assunto": "Crase",
    "enunciado": "8. Assinale a alternativa em que o uso (ou a ausência) do acento indicativo de crase está de acordo com a norma-padrão:",
    "alternativas": [
      "A proposta foi encaminhada à Diretoria de Gestão de Riscos.",
      "A auditoria será realizada à partir da próxima semana.",
      "O gestor referiu-se à um novo protocolo de segurança.",
      "Esse procedimento é semelhante à aquele adotado no trimestre anterior.",
      "Cabe à cada supervisor revisar os planos de contingência de sua equipe."
    ],
    "corretaIndex": 0,
    "regra": "Crase pela fusão da preposição 'a' com o artigo feminino de 'Diretoria'. Não há crase em 'a partir de' (B), antes de masculino (C), antes de 'aquele' masculino (D) nem antes de 'cada' (E).",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q8"
  },
  {
    "id": 10019,
    "materia": "Português",
    "assunto": "Coesão e Coerência",
    "enunciado": "9. Considere o período: 'A manutenção preditiva reduz a probabilidade de falhas graves; __________, ela não garante a eliminação total dos riscos operacionais.' A conjunção que preenche corretamente a lacuna é:",
    "alternativas": [
      "porque",
      "portanto",
      "no entanto",
      "isto é",
      "ou seja"
    ],
    "corretaIndex": 2,
    "regra": "O segundo segmento contrapõe uma ressalva — relação adversativa, marcada por 'no entanto'. 'Porque' seria causa; 'portanto', conclusão; 'isto é'/'ou seja' são explicativos, não encaixando a oposição do período.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q9"
  },
  {
    "id": 10020,
    "materia": "Português",
    "assunto": "Reescrita / Vozes verbais",
    "enunciado": "10. A frase 'A auditoria identificou diversas não conformidades no processo.' está na voz ativa. Assinale a transposição correta para a voz passiva analítica, preservando sentido e tempo verbal:",
    "alternativas": [
      "Diversas não conformidades identificaram a auditoria no processo.",
      "Diversas não conformidades foram identificadas pela auditoria no processo.",
      "A auditoria foi identificada por diversas não conformidades no processo.",
      "Diversas não conformidades tinham identificado a auditoria no processo.",
      "Identificaram-se diversas não conformidades pela auditoria no processo."
    ],
    "corretaIndex": 1,
    "regra": "Na passiva analítica, o objeto direto vira sujeito paciente, o verbo passa a 'ser' no mesmo tempo + particípio concordando ('foram identificadas'), e o sujeito da ativa vira agente da passiva ('pela auditoria'). (C) inverte papéis; (D) muda o tempo; (E) mistura passiva pronominal com agente da passiva explícito.",
    "fonte": "Simulado diário (inédita) — Português, Rodada 5 — 2026-09-27",
    "fonteUrl": "https://claude.ai/artifact/4KF3YoRGLf8LhRJFk6MFDo",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-27",
    "idOrigem": "Língua Portuguesa|R5|Q10"
  },
  {
    "id": 10021,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "Comunicação Organizacional",
    "enunciado": "1. A área de comunicação da Transpetro divulgou, em veículos de grande circulação, uma campanha destacando os investimentos da empresa em segurança operacional e sustentabilidade, sem qualquer menção a produtos, preços ou promoções comerciais. Essa iniciativa é um exemplo de comunicação:",
    "alternativas": [
      "mercadológica, pois visa diretamente aumentar as vendas dos produtos da empresa.",
      "institucional, pois busca construir e fortalecer a imagem e a credibilidade da organização perante o público.",
      "interna, pois destina-se exclusivamente aos empregados da empresa.",
      "informal, pois ocorre fora dos canais oficiais da organização.",
      "mercadológica, pois toda publicidade em veículos de grande circulação tem finalidade comercial."
    ],
    "corretaIndex": 1,
    "regra": "A comunicação institucional constrói e fortalece a imagem e a credibilidade da organização perante o público, sem foco em vendas — diferente da mercadológica (Marketing) e da interna (dirigida aos empregados).",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q1"
  },
  {
    "id": 10022,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "Trabalho em Equipe — Tuckman",
    "enunciado": "2. Um novo comitê de melhoria contínua foi formado na Transpetro. Nas primeiras reuniões, os membros ainda não haviam definido papéis claros e agiam com certa cautela e formalidade, buscando compreender os limites e expectativas do grupo. Segundo o modelo de desenvolvimento de equipes de Tuckman, esse comitê encontra-se no estágio de:",
    "alternativas": [
      "Tormenta (storming)",
      "Formação (forming)",
      "Normatização (norming)",
      "Atuação (performing)",
      "Interrupção (adjourning)"
    ],
    "corretaIndex": 1,
    "regra": "O modelo de Tuckman: Formação (sem papéis definidos, cautela inicial); Tormenta (conflitos); Normatização (coesão); Atuação (maturidade); Interrupção (dissolução). A ausência de papéis e a cautela caracterizam a Formação.",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q2"
  },
  {
    "id": 10023,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "Equipes Autogerenciadas",
    "enunciado": "3. Em determinada unidade operacional, uma equipe passou a assumir integralmente responsabilidades antes exercidas por um supervisor direto, incluindo o planejamento do ritmo de trabalho, a distribuição de tarefas entre os membros e a solução de problemas do dia a dia, sem que houvesse chefia imediata acompanhando a rotina. Essa configuração caracteriza uma equipe:",
    "alternativas": [
      "virtual, pois seus membros trabalham em locais fisicamente distantes.",
      "funcional cruzada, pois reúne especialistas de diferentes áreas técnicas.",
      "autogerenciada, pois assume responsabilidades de supervisão sem chefia direta.",
      "de projeto temporária, pois é dissolvida ao final de uma entrega específica.",
      "hierárquica tradicional, pois mantém um único responsável formal pelas decisões."
    ],
    "corretaIndex": 2,
    "regra": "Equipes autogerenciadas assumem responsabilidades de supervisão sem chefia direta — planejamento, distribuição de tarefas e solução de problemas — características centrais no enunciado.",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q3"
  },
  {
    "id": 10024,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "Motivação — Maslow",
    "enunciado": "4. Um colaborador que já possui estabilidade financeira, bom relacionamento com a equipe e reconhecimento consistente por parte de seus superiores passa a buscar, em sua trajetória profissional, desafios que lhe permitam desenvolver plenamente seu potencial e expressar sua criatividade no trabalho. Segundo a hierarquia das necessidades de Maslow, esse colaborador está motivado, neste momento, pela necessidade de:",
    "alternativas": [
      "segurança",
      "sociais (associação)",
      "estima",
      "autorrealização",
      "fisiológicas"
    ],
    "corretaIndex": 3,
    "regra": "Maslow ordena: fisiológicas, segurança, sociais, estima e autorrealização (topo — desenvolvimento pleno do potencial). Como as demais já estão satisfeitas, resta a autorrealização.",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q4"
  },
  {
    "id": 10025,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "Motivação — Herzberg",
    "enunciado": "5. Uma empresa aumentou os salários e melhorou as condições físicas do ambiente de trabalho de seus empregados, mas não observou aumento correspondente no nível de motivação e satisfação da equipe — apenas uma redução das reclamações. De acordo com a Teoria dos Dois Fatores de Herzberg, essa situação ocorre porque salário e condições de trabalho são fatores:",
    "alternativas": [
      "motivacionais, que geram satisfação quando presentes",
      "higiênicos, que evitam a insatisfação, mas não geram satisfação por si só",
      "motivacionais, relacionados diretamente ao reconhecimento e à realização pessoal",
      "higiênicos, que aumentam diretamente a produtividade quando melhorados",
      "intrínsecos, ligados diretamente ao conteúdo e ao desafio do próprio cargo"
    ],
    "corretaIndex": 1,
    "regra": "Fatores higiênicos (salário, condições físicas) evitam insatisfação, mas não geram satisfação por si sós. Fatores motivacionais (realização, reconhecimento) geram satisfação genuína.",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q5"
  },
  {
    "id": 10026,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "McGregor — Teoria X e Y",
    "enunciado": "6. Um gestor acredita que seus subordinados, por natureza, evitam responsabilidades e o trabalho sempre que possível, necessitando de supervisão rígida, controle constante e ameaça de punição para que os objetivos organizacionais sejam atingidos. Essa visão corresponde, segundo McGregor, à:",
    "alternativas": [
      "Teoria Y, de perspectiva otimista sobre o trabalhador",
      "Teoria X, de perspectiva pessimista sobre o trabalhador",
      "Liderança situacional, adaptada à maturidade dos liderados",
      "Teoria da Contingência estrutural de Lawrence e Lorsch",
      "Abordagem contingencial de Fiedler, baseada no favorecimento situacional"
    ],
    "corretaIndex": 1,
    "regra": "McGregor: Teoria X (pessimista, controle rígido) e Teoria Y (otimista, autonomia). O enunciado descreve exatamente a Teoria X.",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q6"
  },
  {
    "id": 10027,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "Liderança Situacional",
    "enunciado": "7. Um servidor recém-admitido, ainda pouco familiarizado com os processos e rotinas do setor, apresenta baixa maturidade profissional para a execução de determinada tarefa. Segundo o modelo de Liderança Situacional de Hersey e Blanchard, o estilo de liderança mais adequado nesse caso, para essa tarefa específica, é aquele que:",
    "alternativas": [
      "delega totalmente a tarefa, sem qualquer orientação ou acompanhamento da execução",
      "oferece orientação clara e detalhada, com supervisão mais próxima da execução",
      "compartilha ideias e facilita a tomada de decisão em conjunto, sem qualquer direcionamento",
      "deve ser idêntico ao aplicado a servidores experientes, pois o estilo de liderança não deve variar",
      "é definido exclusivamente pela cultura organizacional, independentemente da maturidade do liderado"
    ],
    "corretaIndex": 1,
    "regra": "Em Hersey e Blanchard, para baixa maturidade o estilo mais adequado é o diretivo, com orientação clara e supervisão próxima.",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q7"
  },
  {
    "id": 10028,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "Justiça Organizacional",
    "enunciado": "8. Um empregado considerou justo o valor da bonificação recebida ao final do ano, condizente com sua produtividade; entretanto, ficou insatisfeito com a forma como o processo de avaliação de desempenho foi conduzido, por não ter tido oportunidade de contestar os critérios utilizados antes da decisão final. Nesse caso, o empregado percebeu justiça na dimensão ______, mas não na dimensão ______.",
    "alternativas": [
      "processual / distributiva",
      "distributiva / processual",
      "interacional / distributiva",
      "processual / interacional",
      "distributiva / interacional"
    ],
    "corretaIndex": 1,
    "regra": "Justiça distributiva (equidade nas recompensas — houve) e processual (justiça dos procedimentos — faltou, pois não pôde contestar critérios).",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q8"
  },
  {
    "id": 10029,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "Gestão do Conhecimento — Processos",
    "enunciado": "9. Após concluir um projeto de grande complexidade técnica, a equipe responsável organizou um workshop para documentar as lições aprendidas, os problemas enfrentados e as soluções encontradas, tornando esse conhecimento disponível em um repositório acessível a outras equipes da empresa. Segundo o modelo dos processos de gestão do conhecimento (Probst, Raub e Romhardt), essa etapa corresponde principalmente a:",
    "alternativas": [
      "identificação",
      "desenvolvimento",
      "compartilhamento/distribuição",
      "utilização",
      "avaliação"
    ],
    "corretaIndex": 2,
    "regra": "O modelo de Probst, Raub e Romhardt tem sete processos; tornar o conhecimento acessível a outras equipes caracteriza o compartilhamento/distribuição.",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q9"
  },
  {
    "id": 10030,
    "materia": "Administração de RH / Processos Administrativos",
    "assunto": "Conhecimento Tácito x Explícito",
    "enunciado": "10. Um técnico com 20 anos de experiência na operação de um terminal aquaviário desenvolveu, ao longo do tempo, uma sensibilidade apurada para identificar sinais sutis de anomalias em equipamentos — uma habilidade que ele tem dificuldade de descrever integralmente em manuais ou procedimentos escritos. Esse tipo de conhecimento é classificado como:",
    "alternativas": [
      "explícito, pois está integralmente documentado nos procedimentos operacionais padrão",
      "tácito, pois está enraizado na experiência pessoal e é de difícil formalização",
      "organizacional, pois pertence exclusivamente à empresa, e não ao indivíduo",
      "processual, pois decorre unicamente dos processos formais de treinamento",
      "codificado, pois pode ser transferido facilmente por meio de manuais e apostilas"
    ],
    "corretaIndex": 1,
    "regra": "Conhecimento tácito está enraizado na experiência pessoal, difícil de formalizar — exatamente a sensibilidade do técnico.",
    "fonte": "Simulado diário (inédita) — Administração de RH / Processos Administrativos, Rodada 4 — 2026-09-19",
    "fonteUrl": "https://claude.ai/artifact/Q6CXUwgepvHrDPnttWqgx6",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-19",
    "idOrigem": "Administração de RH / Processos Administrativos|R4|Q10"
  },
  {
    "id": 10031,
    "materia": "Matemática Financeira",
    "assunto": "Regra dos 72",
    "enunciado": "1. Um capital foi aplicado a juros compostos, a uma taxa de 9% ao ano. Utilizando a Regra dos 72 (aproximação prática para estimar o tempo de duplicação de um capital), o número aproximado de anos necessário para que esse capital dobre de valor é de:",
    "alternativas": [
      "6 anos",
      "7 anos",
      "8 anos",
      "9 anos",
      "10 anos"
    ],
    "corretaIndex": 2,
    "regra": "72 ÷ 9 = 8 anos.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q1"
  },
  {
    "id": 10032,
    "materia": "Matemática Financeira",
    "assunto": "Taxa proporcional x equivalente",
    "enunciado": "2. Um banco oferece uma linha de crédito a juros simples de 2% ao mês. No regime de juros simples, a taxa proporcional anual correspondente a essa taxa mensal é de:",
    "alternativas": [
      "2% ao ano",
      "12% ao ano",
      "24% ao ano",
      "26,82% ao ano",
      "268,2% ao ano"
    ],
    "corretaIndex": 2,
    "regra": "Em juros simples, taxas proporcionais: 2% × 12 = 24% ao ano.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q2"
  },
  {
    "id": 10033,
    "materia": "Matemática Financeira",
    "assunto": "Juros exatos x comerciais",
    "enunciado": "3. Em operações de curto prazo, o critério de juros comerciais considera o ano com 360 dias, enquanto o critério de juros exatos considera o ano civil real. Para um mesmo capital, taxa e prazo em dias, o valor dos juros simples pelo critério comercial, em comparação ao exato, será:",
    "alternativas": [
      "maior, pois o divisor de 360 dias é menor que 365.",
      "menor, pois o ano comercial sempre supõe menos dias.",
      "igual, pois a taxa anual é a mesma.",
      "imprevisível.",
      "menor, por arredondamento dos meses."
    ],
    "corretaIndex": 0,
    "regra": "Divisor menor (360<365) resulta em juros maiores no critério comercial.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q3"
  },
  {
    "id": 10034,
    "materia": "Matemática Financeira",
    "assunto": "TIR",
    "enunciado": "4. Um projeto exige desembolso inicial de R$ 10.000,00 e gera entrada de R$ 12.000,00 ao final de 1 ano. A TIR desse projeto é de:",
    "alternativas": [
      "10% ao ano",
      "15% ao ano",
      "18% ao ano",
      "20% ao ano",
      "24% ao ano"
    ],
    "corretaIndex": 3,
    "regra": "−10.000+12.000/(1+i)=0 → i=20%.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q4"
  },
  {
    "id": 10035,
    "materia": "Matemática Financeira",
    "assunto": "Perpetuidade",
    "enunciado": "5. Uma perpetuidade paga R$ 800,00 por mês, indefinidamente, com o primeiro pagamento em um mês. À taxa de 2% ao mês, o valor presente é de:",
    "alternativas": [
      "R$ 16.000,00",
      "R$ 26.667,00",
      "R$ 32.000,00",
      "R$ 40.000,00",
      "R$ 48.000,00"
    ],
    "corretaIndex": 3,
    "regra": "VP=PMT/i=800/0,02=40.000.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q5"
  },
  {
    "id": 10036,
    "materia": "Matemática Financeira",
    "assunto": "Sistema de Amortização Misto",
    "enunciado": "6. No SAM, o valor de cada prestação corresponde:",
    "alternativas": [
      "à prestação do SAC.",
      "à prestação da Price.",
      "à média aritmética, período a período, entre SAC e Price.",
      "à maior entre as duas.",
      "à soma dividida pelo total de parcelas."
    ],
    "corretaIndex": 2,
    "regra": "SAM = média aritmética das prestações do SAC e da Price, período a período.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q6"
  },
  {
    "id": 10037,
    "materia": "Matemática Financeira",
    "assunto": "Anuidade antecipada x postecipada",
    "enunciado": "7. Duas séries uniformes têm mesmo número de parcelas, prestação e taxa. Série A antecipada, Série B postecipada. Sobre os valores presentes:",
    "alternativas": [
      "VP(A) sempre maior que VP(B).",
      "sempre iguais.",
      "VP(B) sempre maior.",
      "independe do momento do 1º pagamento.",
      "depende só da taxa."
    ],
    "corretaIndex": 0,
    "regra": "VP(antecipada)=VP(postecipada)×(1+i), sempre maior para i positivo.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q7"
  },
  {
    "id": 10038,
    "materia": "Matemática Financeira",
    "assunto": "VPL de fluxo irregular",
    "enunciado": "8. Projeto com investimento de R$ 12.000,00 e fluxos de R$ 4.000/5.000/7.000 (anos 1-3). TMA 10%, fatores 0,909/0,826/0,751. O VPL é de aproximadamente:",
    "alternativas": [
      "R$ 877,00",
      "R$ 1.023,00",
      "R$ 1.500,00",
      "-R$ 1.023,00",
      "R$ 13.023,00"
    ],
    "corretaIndex": 1,
    "regra": "VP=13.023; VPL=13.023-12.000=1.023.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q8"
  },
  {
    "id": 10039,
    "materia": "Matemática Financeira",
    "assunto": "Capitalização diária",
    "enunciado": "9. Juros compostos com capitalização diária de 0,1% ao dia (mês de 30 dias). A taxa mensal equivalente é de aproximadamente:",
    "alternativas": [
      "3,00% ao mês",
      "3,04% ao mês",
      "3,30% ao mês",
      "3,45% ao mês",
      "30,00% ao mês"
    ],
    "corretaIndex": 1,
    "regra": "(1,001)^30-1≈3,04%.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q9"
  },
  {
    "id": 10040,
    "materia": "Matemática Financeira",
    "assunto": "Custo Efetivo Total",
    "enunciado": "10. O indicador de divulgação obrigatória que expressa o custo real total de uma operação de crédito, incorporando juros e encargos, é:",
    "alternativas": [
      "Taxa Selic",
      "Taxa DI",
      "Custo Efetivo Total (CET)",
      "Taxa Referencial (TR)",
      "IPCA"
    ],
    "corretaIndex": 2,
    "regra": "CET é o indicador obrigatório que soma juros + tarifas + seguros + impostos.",
    "fonte": "Simulado diário (inédita) — Matemática Financeira, Rodada 4 — 2026-09-22",
    "fonteUrl": "https://claude.ai/artifact/HpgDnEdRNyCX9KhfAepjup",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-22",
    "idOrigem": "Matemática Financeira|R4|Q10"
  },
  {
    "id": 10041,
    "materia": "Contabilidade",
    "assunto": "Partidas Dobradas",
    "enunciado": "1. De acordo com o método das partidas dobradas, todo lançamento contábil envolve, no mínimo, duas contas, sendo os valores totais de débito sempre iguais aos valores totais de crédito. Considerando a natureza normal (crescente) das contas patrimoniais, assinale a alternativa correta:",
    "alternativas": [
      "Contas do Ativo aumentam por lançamentos a crédito, e contas do Passivo aumentam por lançamentos a débito.",
      "Contas do Ativo aumentam por lançamentos a débito, e contas do Passivo e do Patrimônio Líquido aumentam por lançamentos a crédito.",
      "Tanto o Ativo quanto o Passivo aumentam exclusivamente por lançamentos a débito.",
      "A soma dos débitos de um lançamento pode ser diferente da soma dos créditos, desde que a diferença seja registrada em conta de compensação.",
      "O método das partidas dobradas aplica-se apenas às contas de resultado (receitas e despesas), não às contas patrimoniais."
    ],
    "corretaIndex": 1,
    "regra": "Pelo método das partidas dobradas (Frei Luca Pacioli), contas de natureza devedora (Ativo e Despesas) aumentam a débito e diminuem a crédito; contas de natureza credora (Passivo, Patrimônio Líquido e Receitas) aumentam a crédito e diminuem a débito. O total de débitos de um lançamento é sempre igual ao total de créditos. O método se aplica a todas as contas, patrimoniais e de resultado.",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q1"
  },
  {
    "id": 10042,
    "materia": "Contabilidade",
    "assunto": "Estrutura Conceitual (CPC 00) — Ativo",
    "enunciado": "2. Segundo a Estrutura Conceitual para Elaboração e Divulgação de Relatório Contábil-Financeiro (CPC 00 R2), um Ativo é definido como:",
    "alternativas": [
      "uma obrigação presente da entidade de transferir recursos econômicos como resultado de eventos passados.",
      "um recurso econômico presente controlado pela entidade como resultado de eventos passados, sendo recurso econômico um direito que tem o potencial de produzir benefícios econômicos.",
      "qualquer bem tangível registrado pelo custo histórico, independentemente de seu potencial de gerar benefícios futuros.",
      "o valor residual dos recursos da entidade após a dedução de todas as suas obrigações perante terceiros.",
      "exclusivamente os bens de propriedade legal da entidade, excluindo direitos contratuais de uso."
    ],
    "corretaIndex": 1,
    "regra": "O CPC 00 (R2) define ativo como um recurso econômico presente controlado pela entidade como resultado de eventos passados. Exige apenas controle (não propriedade legal) e potencial de benefício futuro. (A) descreve passivo; (D) descreve PL; (C) erra ao exigir só tangibilidade; (E) erra ao exigir propriedade legal.",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q2"
  },
  {
    "id": 10043,
    "materia": "Contabilidade",
    "assunto": "Estrutura da DRE",
    "enunciado": "3. Na estrutura da Demonstração do Resultado do Exercício (DRE), conforme a Lei 6.404/76, assinale a alternativa que apresenta a sequência correta dos elementos, do topo até o Lucro Líquido do Exercício:",
    "alternativas": [
      "Receita Líquida, Receita Bruta, Lucro Bruto, Custo das Mercadorias Vendidas, Despesas Operacionais, Lucro Líquido.",
      "Receita Bruta, Deduções da Receita Bruta, Receita Líquida, Custo das Mercadorias/Serviços Vendidos, Lucro Bruto, Despesas Operacionais, Resultado Financeiro, Resultado antes do IR/CSLL, IR e CSLL, Lucro Líquido do Exercício.",
      "Lucro Bruto, Receita Bruta, Custo das Mercadorias Vendidas, Receita Líquida, IR e CSLL, Despesas Operacionais, Lucro Líquido.",
      "Receita Bruta, IR e CSLL, Deduções da Receita Bruta, Receita Líquida, Custo das Mercadorias Vendidas, Lucro Bruto, Lucro Líquido.",
      "Despesas Operacionais, Receita Bruta, Receita Líquida, Custo das Mercadorias Vendidas, Lucro Bruto, Resultado Financeiro, Lucro Líquido."
    ],
    "corretaIndex": 1,
    "regra": "A DRE (art. 187 da Lei 6.404/76) segue: Receita Bruta (–) Deduções = Receita Líquida (–) CMV/CSV = Lucro Bruto (–) Despesas Operacionais (+/–) Resultado Financeiro = Resultado antes do IR/CSLL (–) IR/CSLL = Lucro Líquido.",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q3"
  },
  {
    "id": 10044,
    "materia": "Contabilidade",
    "assunto": "Conta Retificadora — PECLD",
    "enunciado": "4. A Estimativa para Perdas Esperadas com Créditos de Liquidação Duvidosa (PECLD, antiga Provisão para Devedores Duvidosos) é registrada contabilmente como uma conta:",
    "alternativas": [
      "do Passivo Circulante, pois representa uma obrigação da empresa perante terceiros.",
      "retificadora do Ativo (conta redutora), diminuindo o saldo de Contas a Receber para refletir seu valor recuperável estimado.",
      "de resultado, classificada exclusivamente como Receita Não Operacional.",
      "do Patrimônio Líquido, registrada como uma reserva de contingência.",
      "do Ativo Não Circulante, independentemente do prazo de vencimento dos créditos correspondentes."
    ],
    "corretaIndex": 1,
    "regra": "A PECLD é conta retificadora (redutora) do Ativo Circulante, subtraída de Contas a Receber (princípio da prudência — CPC 00/CPC 38).",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q4"
  },
  {
    "id": 10045,
    "materia": "Contabilidade",
    "assunto": "Avaliação de Estoques — PEPS x UEPS",
    "enunciado": "5. Em relação aos métodos de avaliação de estoques admitidos pela legislação tributária e pelas normas contábeis brasileiras, é correto afirmar que:",
    "alternativas": [
      "o método UEPS é o mais utilizado no Brasil, por resultar em menor Imposto de Renda em cenários de inflação.",
      "o método PEPS é vedado pela legislação tributária brasileira, sendo permitido apenas o Custo Médio Ponderado.",
      "o CPC 16 veda a utilização do método UEPS para fins contábeis no Brasil, sendo os métodos admitidos o PEPS e o Custo Médio Ponderado.",
      "os três métodos produzem exatamente o mesmo valor de estoque final e de CMV, independentemente da variação de preços no período.",
      "o método do Custo Médio Ponderado é vedado pelas normas contábeis brasileiras."
    ],
    "corretaIndex": 2,
    "regra": "O CPC 16 veda o uso do UEPS no Brasil. Métodos admitidos: PEPS e Custo Médio Ponderado (ou identificação específica).",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q5"
  },
  {
    "id": 10046,
    "materia": "Contabilidade",
    "assunto": "Ativo Não Circulante — subgrupos",
    "enunciado": "6. De acordo com a Lei 6.404/76 (com as alterações das Leis 11.638/2007 e 11.941/2009), o grupo do Ativo Não Circulante é subdividido, no Balanço Patrimonial, nos seguintes subgrupos:",
    "alternativas": [
      "Disponível, Créditos, Estoques e Despesas Antecipadas.",
      "Ativo Realizável a Longo Prazo, Investimentos, Imobilizado e Intangível.",
      "Passivo Circulante, Passivo Não Circulante e Patrimônio Líquido.",
      "Capital Social, Reservas de Capital e Reservas de Lucros.",
      "Receitas Operacionais, Receitas Financeiras e Receitas Não Operacionais."
    ],
    "corretaIndex": 1,
    "regra": "O Ativo Não Circulante (art. 179) compreende: Realizável a Longo Prazo, Investimentos, Imobilizado e Intangível.",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q6"
  },
  {
    "id": 10047,
    "materia": "Contabilidade",
    "assunto": "Liquidez Geral x Liquidez Imediata",
    "enunciado": "7. Um analista deseja avaliar, primeiro, a capacidade da empresa de honrar TODAS as suas obrigações — de curto E de longo prazo — com os recursos disponíveis a curto e longo prazo e, em seguida, a capacidade de pagamento imediato, considerando apenas as disponibilidades. Os índices adequados são, respectivamente:",
    "alternativas": [
      "Liquidez Corrente e Liquidez Seca.",
      "Liquidez Seca e Liquidez Corrente.",
      "Liquidez Geral e Liquidez Imediata.",
      "Liquidez Imediata e Liquidez Geral.",
      "Liquidez Corrente e Liquidez Geral."
    ],
    "corretaIndex": 2,
    "regra": "Liquidez Geral = (AC + Realizável a LP)/(PC+PNC). Liquidez Imediata = Disponível/PC.",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q7"
  },
  {
    "id": 10048,
    "materia": "Contabilidade",
    "assunto": "Rentabilidade — ROE",
    "enunciado": "8. O índice que mede o retorno gerado pela empresa sobre os recursos próprios investidos pelos acionistas/sócios, calculado pela razão entre o Lucro Líquido e o Patrimônio Líquido do período, é conhecido como:",
    "alternativas": [
      "ROA (Return on Assets)",
      "ROE (Return on Equity)",
      "EBITDA",
      "Índice de Liquidez Geral",
      "Giro do Ativo"
    ],
    "corretaIndex": 1,
    "regra": "ROE = Lucro Líquido / Patrimônio Líquido mede rentabilidade sob a ótica do acionista.",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q8"
  },
  {
    "id": 10049,
    "materia": "Contabilidade",
    "assunto": "Demonstração das Mutações do PL",
    "enunciado": "9. A demonstração contábil que evidencia a movimentação de todas as contas do Patrimônio Líquido ao longo do exercício é a:",
    "alternativas": [
      "Demonstração do Fluxo de Caixa (DFC)",
      "Demonstração do Resultado Abrangente (DRA)",
      "Demonstração das Mutações do Patrimônio Líquido (DMPL)",
      "Demonstração do Valor Adicionado (DVA)",
      "Balanço Patrimonial"
    ],
    "corretaIndex": 2,
    "regra": "A DMPL evidencia a movimentação de todas as contas do PL no período.",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q9"
  },
  {
    "id": 10050,
    "materia": "Contabilidade",
    "assunto": "Ajuste a Valor Presente (CPC 12)",
    "enunciado": "10. Uma empresa vendeu mercadorias a prazo, com recebimento previsto para 12 meses, sem taxa de juros explicitamente pactuada em contrato. De acordo com o CPC 12, essa operação deve ser tratada contabilmente da seguinte forma:",
    "alternativas": [
      "o valor da venda deve ser registrado pelo valor nominal, sem qualquer ajuste, já que não há previsão contratual de juros.",
      "o valor da venda deve ser ajustado a valor presente, reconhecendo a diferença como receita financeira ao longo do prazo.",
      "o Ajuste a Valor Presente aplica-se exclusivamente a operações de longo prazo, nunca até 12 meses.",
      "o Ajuste a Valor Presente deve ser reconhecido diretamente no Patrimônio Líquido, sem transitar pelo resultado.",
      "o Ajuste a Valor Presente somente é exigido quando há taxa de juros expressamente pactuada em contrato."
    ],
    "corretaIndex": 1,
    "regra": "O CPC 12 exige ajuste a valor presente mesmo sem juros explícitos — há juros implícitos no preço a prazo, reconhecidos como receita financeira pelo resultado.",
    "fonte": "Simulado diário (inédita) — Contabilidade, Rodada 4 — 2026-09-23",
    "fonteUrl": "https://claude.ai/artifact/N7bniYRmidkERdyxsd8E2s",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-23",
    "idOrigem": "Contabilidade|R4|Q10"
  },
  {
    "id": 10051,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "Modal Rodoviário",
    "enunciado": "1. A Transpetro precisa transportar peças de reposição de pequeno porte entre um almoxarifado central e diversas bases de distribuição regionais, com necessidade de entrega porta a porta e rotas flexíveis. Nesse cenário, o modal mais adequado é o:",
    "alternativas": [
      "Dutoviário, por ser o mais econômico para qualquer distância.",
      "Rodoviário, por oferecer flexibilidade de rotas e capilaridade para entregas porta a porta.",
      "Ferroviário, por ter menor custo fixo de implantação.",
      "Aquaviário, por permitir maior capacidade de carga por unidade transportada.",
      "Aéreo, por ser o modal com menor custo por tonelada-quilômetro."
    ],
    "corretaIndex": 1,
    "regra": "O modal rodoviário se destaca pela flexibilidade de rotas e capilaridade — ideal para cargas fracionadas e curtas/médias distâncias.",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q1"
  },
  {
    "id": 10052,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "Modal Aéreo",
    "enunciado": "2. Em relação ao modal aéreo de transporte de cargas, é correto afirmar que:",
    "alternativas": [
      "apresenta o menor custo por tonelada transportada entre todos os modais.",
      "é o modal mais indicado para o transporte de granéis sólidos de baixo valor agregado.",
      "caracteriza-se por alta velocidade e é indicado para cargas de alto valor agregado, urgência ou perecibilidade, apesar do custo elevado.",
      "possui a maior capilaridade entre os modais.",
      "dispensa embalagem adequada."
    ],
    "corretaIndex": 2,
    "regra": "O modal aéreo tem altíssima velocidade, adequado a cargas de alto valor, urgentes ou perecíveis, apesar do custo elevado; tem baixa capilaridade.",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q2"
  },
  {
    "id": 10053,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "Armazenagem (Slotting)",
    "enunciado": "3. No planejamento do layout de um armazém, a técnica conhecida como \"slotting\" consiste em:",
    "alternativas": [
      "eliminar completamente a necessidade de estoques de segurança.",
      "definir a localização mais adequada de cada item no armazém, considerando giro, volume e frequência de coleta, para otimizar o picking.",
      "transferir ao fornecedor a responsabilidade pelo gerenciamento do estoque do cliente.",
      "consolidar cargas de diferentes fornecedores em um único veículo de transporte.",
      "padronizar embalagens para permitir empilhamento uniforme nas docas."
    ],
    "corretaIndex": 1,
    "regra": "Slotting define a melhor localização de cada SKU no armazém, considerando giro, volume e frequência de movimentação.",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q3"
  },
  {
    "id": 10054,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "VMI",
    "enunciado": "4. Em um modelo de reposição de estoque no qual o próprio fornecedor monitora os níveis de estoque do cliente e decide quando e quanto repor, tem-se a prática conhecida como:",
    "alternativas": [
      "Cross-docking",
      "Just in Time",
      "VMI (Vendor Managed Inventory)",
      "Milk-run",
      "Outsourcing logístico"
    ],
    "corretaIndex": 2,
    "regra": "O VMI transfere ao fornecedor a responsabilidade de monitorar e repor o estoque do cliente.",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q4"
  },
  {
    "id": 10055,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "CPFR",
    "enunciado": "5. A sigla CPFR, prática colaborativa na cadeia de suprimentos, refere-se a:",
    "alternativas": [
      "Planejamento, Previsão e Reposição Colaborativos entre parceiros da cadeia.",
      "Certificação de Processos e Fluxos de Recebimento em armazéns.",
      "Controle de Perdas e Faltas em Rotas de distribuição.",
      "Cadeia de Produção e Fornecimento Reversa.",
      "Custo de Processamento e Frete Rodoviário."
    ],
    "corretaIndex": 0,
    "regra": "CPFR (Collaborative Planning, Forecasting and Replenishment) reduz o efeito chicote e melhora a acuracidade do abastecimento.",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q5"
  },
  {
    "id": 10056,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "Incoterms (EXW/DDP)",
    "enunciado": "6. Considerando os Incoterms 2020, a modalidade em que o vendedor assume o MÍNIMO de responsabilidades e custos é a:",
    "alternativas": [
      "DDP (Delivered Duty Paid)",
      "CIF (Cost, Insurance and Freight)",
      "EXW (Ex Works)",
      "FOB (Free on Board)",
      "CFR (Cost and Freight)"
    ],
    "corretaIndex": 2,
    "regra": "O EXW representa a menor obrigação do vendedor; o DDP representa o máximo.",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q6"
  },
  {
    "id": 10057,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "Postponement",
    "enunciado": "7. Uma indústria decide finalizar a customização de determinado produto apenas na etapa mais próxima possível da entrega ao cliente final. Essa estratégia é conhecida como:",
    "alternativas": [
      "Cross-docking",
      "Postponement (postergação)",
      "Milk-run",
      "Consolidação de cargas",
      "Curva ABC"
    ],
    "corretaIndex": 1,
    "regra": "Postponement adia a diferenciação/customização final do produto até o ponto mais próximo possível da demanda real.",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q7"
  },
  {
    "id": 10058,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "Custo Total de Propriedade (TCO)",
    "enunciado": "8. Ao avaliar propostas de fornecedores, uma empresa considera não apenas o preço de compra, mas custos de transporte, armazenagem, manutenção, qualidade e descarte ao longo do ciclo de vida do item. Esse método é conhecido como:",
    "alternativas": [
      "Curva ABC",
      "Lote Econômico de Compra (LEC)",
      "Custo Total de Propriedade (TCO)",
      "Ponto de Pedido",
      "Incoterms"
    ],
    "corretaIndex": 2,
    "regra": "O TCO considera todos os custos associados à aquisição e uso de um item ao longo do seu ciclo de vida.",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q8"
  },
  {
    "id": 10059,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "Kanban",
    "enunciado": "9. O sistema Kanban, aplicado à gestão logística e de estoques, tem como principal característica:",
    "alternativas": [
      "centralizar todas as decisões de reposição sem sinalização visual.",
      "utilizar sinais visuais para disparar a reposição de materiais apenas quando efetivamente consumidos, em sistema puxado (pull).",
      "programar a reposição com base exclusivamente em previsões de longo prazo (push).",
      "eliminar a necessidade de qualquer estoque de segurança.",
      "ser aplicável apenas a processos de manufatura."
    ],
    "corretaIndex": 1,
    "regra": "O Kanban é um sistema de sinalização visual que aciona reposição apenas quando consumido — sistema puxado (pull).",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q9"
  },
  {
    "id": 10060,
    "materia": "Logística e Cadeia de Suprimentos",
    "assunto": "Gestão de Compras (Sourcing)",
    "enunciado": "10. Uma empresa decide concentrar a aquisição de determinado insumo estratégico em um único fornecedor, buscando maior poder de negociação, mas assumindo maior exposição a riscos de desabastecimento. Essa estratégia de sourcing é conhecida como:",
    "alternativas": [
      "Multiple sourcing",
      "Single sourcing (fonte única)",
      "Global sourcing",
      "Cross-docking",
      "Just in Time II"
    ],
    "corretaIndex": 1,
    "regra": "O single sourcing concentra as compras em um único fornecedor, aumentando o risco de desabastecimento.",
    "fonte": "Simulado diário (inédita) — Logística e Cadeia de Suprimentos, Rodada 4 — 2026-09-24",
    "fonteUrl": "https://claude.ai/artifact/CmhtvmZXmhNhaFzhn6yJBA",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-24",
    "idOrigem": "Logística e Cadeia de Suprimentos|R4|Q10"
  },
  {
    "id": 10061,
    "materia": "Legislação",
    "assunto": "Vedação de acumulação em conselhos (art. 20, Lei 13.303/2016)",
    "enunciado": "1. Um mesmo servidor público ocupa cargo em dois conselhos de administração de subsidiárias de uma sociedade de economia mista federal, remuneradamente. Convidado a integrar remuneradamente um terceiro conselho fiscal, essa participação, segundo a Lei 13.303/2016:",
    "alternativas": [
      "é permitida, pois a vedação aplica-se somente a conselhos de administração.",
      "é vedada, pois a lei proíbe participação remunerada em mais de 2 conselhos, de administração ou fiscal, de estatais ou subsidiárias.",
      "é permitida, desde que autorizada pelo Ministério supervisor.",
      "é vedada apenas se as empresas atuarem no mesmo setor.",
      "é permitida sem limite, se não houver conflito de interesses declarado."
    ],
    "corretaIndex": 1,
    "regra": "Art. 20 da Lei 13.303/2016: vedada participação remunerada em mais de 2 conselhos (administração ou fiscal) de estatais ou subsidiárias.",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q1"
  },
  {
    "id": 10062,
    "materia": "Legislação",
    "assunto": "Comitê de Auditoria Estatutário (art. 24)",
    "enunciado": "2. Sobre o Comitê de Auditoria Estatutário (CAE) na Lei 13.303/2016, é correto afirmar que ele:",
    "alternativas": [
      "deve ter no mínimo 3 e no máximo 5 membros, maioria independentes.",
      "deve ser composto exclusivamente por diretores da empresa.",
      "pode incluir ex-diretor sem restrição de prazo.",
      "não possui exigência legal de número de membros.",
      "deve ser composto exclusivamente por indicados do controlador."
    ],
    "corretaIndex": 0,
    "regra": "Art. 24: CAE com 3 a 5 membros, maioria independentes; veda diretor/empregado dos últimos 12 meses.",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q2"
  },
  {
    "id": 10063,
    "materia": "Legislação",
    "assunto": "Prazo de gestão e reconduções (art. 13)",
    "enunciado": "3. Um estatuto fixou prazo de gestão de 2 anos com reconduções ilimitadas para o Conselho de Administração. Isso, à luz da Lei 13.303/2016:",
    "alternativas": [
      "está de acordo, sem limite de reconduções.",
      "contraria a lei, prazo máximo de 1 ano.",
      "contraria a lei, que permite no máximo 3 reconduções consecutivas para prazo de até 2 anos.",
      "contraria a lei apenas quanto ao prazo, que deveria ser 4 anos.",
      "está de acordo, com novo processo seletivo a cada recondução."
    ],
    "corretaIndex": 2,
    "regra": "Art. 13: prazo de gestão não superior a 2 anos, permitidas no máximo 3 reconduções consecutivas.",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q3"
  },
  {
    "id": 10064,
    "materia": "Legislação",
    "assunto": "Transparência e governança (art. 8º)",
    "enunciado": "4. Entre as práticas de governança exigidas pela Lei 13.303/2016, inclui-se:",
    "alternativas": [
      "dispensa de carta anual.",
      "elaboração e divulgação de carta anual subscrita pelos administradores e divulgação de política de transações com partes relacionadas.",
      "sigilo absoluto sobre partes relacionadas.",
      "publicação apenas mediante LAI.",
      "divulgação restrita aos acionistas controladores."
    ],
    "corretaIndex": 1,
    "regra": "Art. 8º exige carta anual subscrita pelos administradores e divulgação de política de partes relacionadas.",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q4"
  },
  {
    "id": 10065,
    "materia": "Legislação",
    "assunto": "Conselho Fiscal — requisitos (art. 26)",
    "enunciado": "5. Para integrar o Conselho Fiscal de uma SEM, nos termos da Lei 13.303/2016, requisito é:",
    "alternativas": [
      "ser empregado da empresa há mais de 5 anos.",
      "ser pessoa natural, residente no País, com formação acadêmica compatível.",
      "ter sido indicado obrigatoriamente pelo CAE.",
      "possuir exclusivamente formação em Direito.",
      "ser necessariamente servidor público."
    ],
    "corretaIndex": 1,
    "regra": "Art. 26: pessoa natural, residente no País, formação acadêmica compatível com a função.",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q5"
  },
  {
    "id": 10066,
    "materia": "Legislação",
    "assunto": "Inexigibilidade de licitação (art. 74)",
    "enunciado": "6. A contratação de advogado de notória especialização para processo judicial de alta complexidade, inviável a competição objetiva, configura:",
    "alternativas": [
      "dispensa por valor.",
      "dispensa por emergência.",
      "inexigibilidade, por serviço técnico especializado de natureza intelectual com profissional de notória especialização.",
      "licitação dispensada entre entes públicos.",
      "inexigibilidade por fornecedor exclusivo."
    ],
    "corretaIndex": 2,
    "regra": "Art. 74: inexigível quando inviável a competição, incluindo serviços técnicos especializados de notória especialização.",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q6"
  },
  {
    "id": 10067,
    "materia": "Legislação",
    "assunto": "Fiscal x gestor do contrato (art. 117)",
    "enunciado": "7. Um servidor acompanha a execução técnica e atesta notas fiscais; outro coordena a fiscalização, prorrogações e sanções. Essas funções correspondem a:",
    "alternativas": [
      "gestor e fiscal.",
      "fiscal e gestor.",
      "pregoeiro e agente de contratação.",
      "agente de contratação e fiscal.",
      "fiscal e pregoeiro."
    ],
    "corretaIndex": 1,
    "regra": "Fiscal acompanha execução técnica e atesta; gestor coordena fiscalização, prorrogações e sanções.",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q7"
  },
  {
    "id": 10068,
    "materia": "Legislação",
    "assunto": "Reequilíbrio econômico-financeiro (art. 124)",
    "enunciado": "8. Fato imprevisível tornou a execução do contrato extraordinariamente onerosa. O contratado tem direito a:",
    "alternativas": [
      "rescindir unilateralmente, sem outra medida.",
      "manter condições originais sem ajuste.",
      "recomposição/revisão buscando reequilíbrio, com base na teoria da imprevisão.",
      "sanção automática contra a Administração.",
      "reajuste anual obrigatório por inflação."
    ],
    "corretaIndex": 2,
    "regra": "Art. 124: recomposição por fato imprevisível que onere excessivamente uma das partes (teoria da imprevisão).",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q8"
  },
  {
    "id": 10069,
    "materia": "Legislação",
    "assunto": "Contratação integrada x semi-integrada (art. 6º)",
    "enunciado": "9. Um edital estabeleceu que o contratado elaboraria os projetos básico e executivo, executaria a obra e demais operações até a entrega final. Esse regime é:",
    "alternativas": [
      "semi-integrada, apenas projeto executivo.",
      "empreitada por preço unitário.",
      "contratação integrada, projeto básico e executivo mais execução.",
      "credenciamento.",
      "diálogo competitivo."
    ],
    "corretaIndex": 2,
    "regra": "Art. 6º, XXXII: contratação integrada — contratado elabora projetos básico e executivo e executa a obra.",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q9"
  },
  {
    "id": 10070,
    "materia": "Legislação",
    "assunto": "Fase preparatória — ETP e TR (art. 18)",
    "enunciado": "10. A fase preparatória, que compreende ETP e TR, segundo a Lei 14.133/2021:",
    "alternativas": [
      "é dispensável para contratações de baixo valor.",
      "caracteriza-se pelo planejamento e deve compatibilizar-se com o plano de contratações anual.",
      "só é exigida na modalidade concorrência.",
      "é de responsabilidade exclusiva da Advocacia Pública.",
      "substitui a pesquisa de preços."
    ],
    "corretaIndex": 1,
    "regra": "Art. 18: fase preparatória caracterizada pelo planejamento, compatível com o plano de contratações anual.",
    "fonte": "Simulado diário (inédita) — Legislação, Rodada 4 — 2026-09-25",
    "fonteUrl": "https://claude.ai/artifact/Ji2YaUCckovMd6hMNvio9r",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-25",
    "idOrigem": "Legislação|R4|Q10"
  },
  {
    "id": 10071,
    "materia": "Informática",
    "assunto": "Windows 11 — Configurações Rápidas",
    "enunciado": "1. Um usuário do Windows 11 deseja ajustar rapidamente Wi-Fi, volume, brilho e modo avião a partir da barra de tarefas, sem abrir Configurações. Esse recurso é denominado:",
    "alternativas": [
      "Central de Notificações",
      "Configurações Rápidas (Quick Settings)",
      "Widgets",
      "Assistente de Foco",
      "Explorador de Arquivos"
    ],
    "corretaIndex": 1,
    "regra": "\"Configurações Rápidas\" é acessado pelo conjunto de ícones de rede/volume/bateria, oferecendo alternância rápida sem abrir o app Configurações.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q1"
  },
  {
    "id": 10072,
    "materia": "Informática",
    "assunto": "Windows 11 — Windows Update",
    "enunciado": "2. O recurso nativo que permite adiar temporariamente a instalação de novas atualizações do Windows 11 por um período determinado é:",
    "alternativas": [
      "Restauração do Sistema",
      "Pausar atualizações (Pause updates)",
      "Modo de Compatibilidade",
      "Ponto de Restauração Automático",
      "Desfragmentador de Disco"
    ],
    "corretaIndex": 1,
    "regra": "\"Pausar atualizações\" suspende temporariamente (até 5 semanas) a instalação de atualizações, sem desativar o serviço.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q2"
  },
  {
    "id": 10073,
    "materia": "Informática",
    "assunto": "Word — Comparar Documentos",
    "enunciado": "3. Um analista precisa identificar diferenças entre duas versões de um relatório editadas independentemente, gerando um terceiro documento evidenciando as alterações. O recurso do Word, na guia Revisão, é:",
    "alternativas": [
      "Controlar Alterações",
      "Comparar",
      "Referência Cruzada",
      "Painel de Navegação",
      "Verificar Acessibilidade"
    ],
    "corretaIndex": 1,
    "regra": "Revisão > Comparar gera um documento evidenciando diferenças entre dois arquivos já prontos.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q3"
  },
  {
    "id": 10074,
    "materia": "Informática",
    "assunto": "Excel — Formatação Condicional",
    "enunciado": "4. Em uma coluna de valores de estoque, deseja-se destacar automaticamente em vermelho valores inferiores a 10 unidades. O recurso adequado é:",
    "alternativas": [
      "Validação de Dados",
      "Formatação Condicional",
      "Congelar Painéis",
      "Classificação Personalizada",
      "Preenchimento Relâmpago"
    ],
    "corretaIndex": 1,
    "regra": "Formatação Condicional aplica formatação automática às células que atendem a uma regra definida, atualizando-se dinamicamente.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q4"
  },
  {
    "id": 10075,
    "materia": "Informática",
    "assunto": "Excel — Atingir Meta",
    "enunciado": "5. Um analista quer descobrir qual valor uma célula de entrada deve assumir para que uma célula de resultado atinja um valor-alvo. A ferramenta do Excel é:",
    "alternativas": [
      "Solver",
      "Atingir Meta (Goal Seek)",
      "Tabela Dinâmica",
      "Cenários",
      "Consolidar"
    ],
    "corretaIndex": 1,
    "regra": "\"Atingir Meta\" ajusta UMA célula de entrada para que uma fórmula dependente atinja um valor-alvo.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q5"
  },
  {
    "id": 10076,
    "materia": "Informática",
    "assunto": "PowerPoint — Designer",
    "enunciado": "6. Ao inserir imagens e texto em um slide quase em branco, o PowerPoint sugere automaticamente opções de layout em um painel lateral. Esse recurso é:",
    "alternativas": [
      "Slide Mestre",
      "Designer (Ideias de Design)",
      "Transições",
      "Anotações do Apresentador",
      "Compactar Mídia"
    ],
    "corretaIndex": 1,
    "regra": "\"Designer\" analisa o conteúdo do slide e sugere opções de layout profissional.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q6"
  },
  {
    "id": 10077,
    "materia": "Informática",
    "assunto": "Segurança da Informação — Firewall",
    "enunciado": "7. Mecanismo que monitora e controla o tráfego de rede com base em regras predefinidas, atuando como barreira entre rede interna e externa:",
    "alternativas": [
      "Antivírus",
      "Firewall",
      "VPN",
      "Proxy reverso de cache",
      "Honeypot"
    ],
    "corretaIndex": 1,
    "regra": "O firewall monitora e controla tráfego com base em regras de segurança, como barreira entre redes.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q7"
  },
  {
    "id": 10078,
    "materia": "Informática",
    "assunto": "Segurança da Informação — Engenharia Social",
    "enunciado": "8. Um funcionário recebeu ligação de suposto técnico de TI pedindo sua senha, sob pretexto de manutenção emergencial. Essa técnica é:",
    "alternativas": [
      "Ataque de força bruta",
      "Engenharia social",
      "Ataque de negação de serviço (DDoS)",
      "Injeção de SQL",
      "Man-in-the-middle"
    ],
    "corretaIndex": 1,
    "regra": "Engenharia social explora confiança/boa-fé das pessoas; vishing é a modalidade por voz/telefone.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q8"
  },
  {
    "id": 10079,
    "materia": "Informática",
    "assunto": "LGPD — Direitos do Titular (art. 18)",
    "enunciado": "9. Segundo o art. 18 da LGPD, o titular tem direito a obter do controlador, mediante requisição:",
    "alternativas": [
      "acesso mediante pagamento de taxa fixada pela ANPD.",
      "confirmação da existência de tratamento e acesso aos dados.",
      "transferência de sua base de dados para concorrentes.",
      "exclusão definitiva mesmo quando exigida por obrigação legal.",
      "proibição total de qualquer tratamento."
    ],
    "corretaIndex": 1,
    "regra": "Art. 18 assegura confirmação de tratamento, acesso, correção, anonimização/eliminação, portabilidade, sem cobrança de taxa.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q9"
  },
  {
    "id": 10080,
    "materia": "Informática",
    "assunto": "LGPD — Relatório de Impacto (RIPD)",
    "enunciado": "10. Documento do controlador que descreve processos de tratamento capazes de gerar riscos, com medidas de mitigação, previsto nos arts. 5º XVII e 38 da LGPD:",
    "alternativas": [
      "Termo de Consentimento Livre e Esclarecido",
      "Relatório de Impacto à Proteção de Dados Pessoais (RIPD)",
      "Política de Privacidade",
      "Acordo de Cooperação Técnica",
      "Termo de Ajustamento de Conduta (TAC)"
    ],
    "corretaIndex": 1,
    "regra": "O RIPD descreve processos de tratamento de risco, com medidas de mitigação; a ANPD pode determinar sua elaboração.",
    "fonte": "Simulado diário (inédita) — Informática, Rodada 4 — 2026-09-26",
    "fonteUrl": "https://claude.ai/artifact/DxnezrtY5z46bytKxCm2JT",
    "valido": true,
    "origem": "ia",
    "rodada": 4,
    "dataCriacao": "2026-09-26",
    "idOrigem": "Informática|R4|Q10"
  },
  {
    "id": 10081,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Porcentagem",
    "enunciado": "1. Um tanque de armazenamento tem capacidade de 50.000 barris. Após receber uma nova carga, ficou com 68% de sua capacidade ocupada. Em seguida, foi retirado, para envio a uma refinaria, um volume equivalente a 40% do que estava armazenado no tanque. Quantos barris permaneceram no tanque após essa retirada?",
    "alternativas": [
      "13.600 barris",
      "14.000 barris",
      "20.400 barris",
      "30.600 barris",
      "34.000 barris"
    ],
    "corretaIndex": 2,
    "regra": "68% de 50.000 = 34.000 barris armazenados. Retirando 40% desse volume: 40% de 34.000 = 13.600 barris retirados. Volume remanescente: 34.000 − 13.600 = 20.400 barris. A alternativa (A) é o volume retirado, e a (E) é o volume antes da retirada — ambos armadilhas comuns quando se confunde a base percentual.",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q1"
  },
  {
    "id": 10082,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Porcentagem",
    "enunciado": "2. O preço do barril de petróleo subiu 15% em um determinado mês e, no mês seguinte, caiu 10% em relação ao novo valor. A variação percentual acumulada do preço, em relação ao valor inicial (antes do primeiro reajuste), foi de:",
    "alternativas": [
      "+13,5%",
      "+5,0%",
      "+3,5%",
      "−5,0%",
      "+25,0%"
    ],
    "corretaIndex": 2,
    "regra": "Aumentos e descontos sucessivos não se somam algebricamente. O fator acumulado é 1,15 × 0,90 = 1,035, ou seja, uma variação de +3,5% sobre o valor inicial. A alternativa (B) corresponde ao erro comum de somar 15% − 10% = 5%, o que ignora que o segundo percentual incide sobre a base já reajustada.",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q2"
  },
  {
    "id": 10083,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Análise Combinatória",
    "enunciado": "3. Uma comissão de 3 técnicos deve ser formada, dentre 8 técnicos disponíveis, para inspecionar uma plataforma. Sabendo que a ordem de escolha dos membros não importa, de quantas maneiras distintas essa comissão pode ser formada?",
    "alternativas": [
      "24",
      "56",
      "168",
      "336",
      "512"
    ],
    "corretaIndex": 1,
    "regra": "Como a ordem não importa, trata-se de uma combinação simples: C(8,3) = 8!/(3!·5!) = (8×7×6)/(3×2×1) = 336/6 = 56. A alternativa (D), 336, corresponde ao arranjo (permutação) A(8,3), que seria usado caso a ordem dos membros importasse.",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q3"
  },
  {
    "id": 10084,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Juros Compostos",
    "enunciado": "4. Um capital de R$ 20.000,00 foi aplicado a juros compostos de 5% ao mês, durante 2 meses. O montante ao final desse período é de:",
    "alternativas": [
      "R$ 21.000,00",
      "R$ 22.000,00",
      "R$ 22.050,00",
      "R$ 22.100,00",
      "R$ 24.200,00"
    ],
    "corretaIndex": 2,
    "regra": "Em juros compostos, M = C·(1+i)ⁿ = 20.000 × (1,05)² = 20.000 × 1,1025 = R$ 22.050,00. A alternativa (B) é o resultado com juros simples; a (E) resultaria de usar i=10% em vez de (1,05)².",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q4"
  },
  {
    "id": 10085,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Probabilidade",
    "enunciado": "5. Uma caixa de manutenção contém 10 válvulas, das quais 3 apresentam defeito. Retirando-se, ao acaso e sem reposição, 2 válvulas dessa caixa, qual é a probabilidade de que ambas estejam com defeito?",
    "alternativas": [
      "1/15",
      "1/10",
      "1/5",
      "3/10",
      "9/100"
    ],
    "corretaIndex": 0,
    "regra": "P = C(3,2)/C(10,2) = 3/45 = 1/15. A alternativa (E), 9/100, corresponde ao erro de tratar as retiradas como independentes e com reposição, o que não se aplica aqui.",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q5"
  },
  {
    "id": 10086,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Progressão Aritmética",
    "enunciado": "6. Uma linha de produção aumenta sua produção diária em uma quantidade constante a cada dia, formando uma progressão aritmética (PA). No 1º dia foram produzidas 120 unidades e, no 10º dia, 210 unidades. A razão dessa PA é:",
    "alternativas": [
      "8",
      "9",
      "10",
      "12",
      "15"
    ],
    "corretaIndex": 2,
    "regra": "a₁₀ = a₁ + 9r → 210 = 120 + 9r → 9r = 90 → r = 10. Erro comum: dividir por 10 em vez de 9 intervalos, levando à alternativa (B).",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q6"
  },
  {
    "id": 10087,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Progressão Geométrica",
    "enunciado": "7. O volume de óleo extraído por um novo poço dobra a cada mês, formando uma progressão geométrica (PG) de razão 2. Se no 1º mês foram extraídos 500 barris, quantos barris serão extraídos no 5º mês?",
    "alternativas": [
      "2.000 barris",
      "4.000 barris",
      "8.000 barris",
      "10.000 barris",
      "16.000 barris"
    ],
    "corretaIndex": 2,
    "regra": "a₅ = a₁·r⁴ = 500 × 2⁴ = 8.000 barris. A alternativa (E) usa r⁵ em vez de r⁴ (expoente correto é n−1).",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q7"
  },
  {
    "id": 10088,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Regra de Três Composta",
    "enunciado": "8. Trabalhando 8 horas por dia, 5 operários concluem uma tarefa de manutenção em 6 dias. Mantida a mesma produtividade, trabalhando 6 horas por dia, quantos operários serão necessários para concluir a mesma tarefa em 4 dias?",
    "alternativas": [
      "6",
      "8",
      "10",
      "12",
      "15"
    ],
    "corretaIndex": 2,
    "regra": "Trabalho total constante: 5×8×6 = 240. Na nova situação: x×6×4=240 → x=10 operários. Horas/dia e dias são inversamente proporcionais ao número de operários.",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q8"
  },
  {
    "id": 10089,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Raciocínio Lógico (Proposições e Silogismos)",
    "enunciado": "9. Considere as premissas: \"Todo técnico de manutenção usa equipamento de proteção individual (EPI)\" e \"João não usa EPI\". A partir dessas duas premissas, pode-se concluir corretamente que:",
    "alternativas": [
      "João não é técnico de manutenção.",
      "João é técnico de manutenção, mas não usa EPI.",
      "Nenhum técnico de manutenção usa EPI.",
      "Todos que usam EPI são técnicos de manutenção.",
      "Não é possível concluir nada a partir dessas premissas."
    ],
    "corretaIndex": 0,
    "regra": "Pela contrapositiva (modus tollens) de \"Todo A é B\": se João não é B, então João não é A. As demais alternativas invertem ou distorcem essa relação lógica.",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q9"
  },
  {
    "id": 10090,
    "materia": "Matemática e Raciocínio Lógico",
    "assunto": "Estatística Básica (Média, Moda e Mediana)",
    "enunciado": "10. Durante uma auditoria, foram registrados os seguintes tempos de parada de um equipamento, em minutos: 12, 15, 12, 18, 20, 12, 25. A moda e a mediana desse conjunto de dados são, respectivamente:",
    "alternativas": [
      "Moda 12 e mediana 15",
      "Moda 15 e mediana 12",
      "Moda 12 e mediana 18",
      "Moda 25 e mediana 15",
      "Moda 12 e mediana 16,29"
    ],
    "corretaIndex": 0,
    "regra": "Ordenando: 12,12,12,15,18,20,25. Moda = 12 (3 ocorrências). Mediana (7 valores, ímpar) = 4º termo = 15. A alternativa (E) troca mediana por média (16,29).",
    "fonte": "Simulado diário (inédita) — Matemática e Raciocínio Lógico, Rodada 5 — 2026-09-28",
    "fonteUrl": "https://claude.ai/artifact/DmLf4jExYG9CyZt5x9yXYq",
    "valido": true,
    "origem": "ia",
    "rodada": 5,
    "dataCriacao": "2026-09-28",
    "idOrigem": "Matemática / Raciocínio Lógico|R5|Q10"
  }
];
